In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              **options)

In [7]:
M1 = np.array([[23,50],
            [7,12]])
M2 = np.array ([[57,67],
            [99,43]])
M3 = np.array ([[75,21],
            [57,12]])
M4 = np.array ([[87,26],
            [18,24]])

tensor = np.array ([M1,M2,M3,M4])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 24]]])

In [23]:
A = np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])

B = np.array([[17],
              [22],
              [19]])
A@B

array([[1852],
       [2454],
       [4305]])

In [24]:
A = np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])

np.array([A]).T


array([[[ 23],
        [  7],
        [ 57]],

       [[ 50],
        [ 12],
        [ 67]],

       [[ 19],
        [109],
        [ 98]]])