In [2]:
import numpy as np

In [7]:
a = np.array([[1,-1],
[6,4]])

a

array([[ 1, -1],
       [ 6,  4]])

In [5]:
np.linalg.eig(a)

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
        [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]]))